export const sesijaTestna = {
  cfid: "69050",
  cftoken: "E3C30397-3764-4DD2-A65264D21C7A3F6B",
  urltoken: "CFID=69050&CFTOKEN=E3C30397-3764-4DD2-A65264D21C7A3F6B",
  sessionid: "KISS_69050_E3C30397-3764-4DD2-A65264D21C7A3F6B",
  loggedin: "True",
  cookieset: "0",
  ipaddr: "",
  jezik: "srpski",
  baza_podataka: "kiss",
  tip_baze_podataka: "mysql",
  avar_baza_podataka_conf: "kiss",
  id_klijenta: 1,
  naziv_klijenta: "Univerzitetski klinički centar Republike Srpske",
  drzava_klijenta: "RS",
  id_korisnika: 4308,
  ime_korisnika: "Bajić Dejan",
  potpis_korisnika: "Dejan Bajić",
  grupa_korisnika: "2,12,11,21,9,18,3,0,20,22,1",
  funkcija_korisnika: "18,11,23",
  korisnicko_ime: "admindejan",
  sifra_korisnika: "vjIj97o2",
  organizacija: 1012,
  organizacija_naziv: "KLINIKA ZA KARDIOLOGIJU",
  organizacija_sifra: "1012",
  organizacija_odjel: 10126,
  organizacija_odjel_naziv: "Koronarno odjeljenje",
  izabrano_skladiste: 10126,
  izabrana_grupa_skladista: 1012,
  poslovna_godina: 2024,
  obavjestenje: "",
  aplikacija: "bisa_2",
  nacin_rada: "klinika",
  ezdravstvo_korisnicko_ime: null,
  ezdravstvo_lozinka: null,
  izis_ljekar_id: "",
  izis_ljekar_jmbg: "",
  izis_ljekar_ime: "",
  izis_ljekar_prezime: "",
  izis_ustanova_id: "4596",
  izis_ustanova_ime: "Klinika za kardiologiju",
  izis_ustanova_ulica: "Dvanaest beba bb",
  izis_ustanova_grad: "Banja Luka",
  izis_ustanova_ptt_broj: "78000",
  izis_ustanova_drzava: "BA"
}

// eslint-disable-next-line no-unused-vars
const pomocni_objekat = {
  greska: '',
  lista: '',
  verzija: ''
}